# SPDX-FileCopyrightText: 2020 - 2022 Intel
# SPDX-FileCopyrightText: 2021 - 2022 Fraunhofer SIT sponsored by Infineon
# SPDX-FileCopyrightText: 2024 Juergen Repp
# SPDX-License-Identifier: BSD-2-Clause

name: CI
on:
  [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        docker_image: [
          ghcr.io/tpm2-software/fedora-32@sha256:be98523aac16f8d7e0728f775afece31ec8f2730470bb0a8e3e39373ca72e6f7,
          ghcr.io/tpm2-software/opensuse-leap@sha256:55c2da5db51e359a1c462b7a1e9a5a836a51cea1e2f5e70b361304c53568ab80,
          ghcr.io/tpm2-software/ubuntu-22.04@sha256:7ac215b86da42081ab53c717ae6daf62d6eed1303872cd56caebcc2656405cef,
          ghcr.io/tpm2-software/ubuntu-24.04@sha256:36b8cc4ff293ec9e7f748ea98a472c0ace69c75d244b6b84584b53a0805505be,
          ghcr.io/tpm2-software/alpine-3.15@sha256:8fff89b25611240b95759a13d8f374173997097e8a4ede0cb93bc982eb14a8ed,
          ghcr.io/tpm2-software/arch-linux@sha256:288ca6db455f2b55fa3850757cb1e6a5cd401f225497881a2e1a01dea312d020
        ]
        compiler: [gcc, clang]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fix-sanitizer
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          CC: ${{ matrix.compiler }}
          BASE_REF: ${{ github.base_ref }}
          WITH_TCTI: libtpms
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
  scanbuild:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fix-sanitizer
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          CC: clang
          DOCKER_IMAGE: fedora-32
          SCANBUILD: yes
          WITH_TCTI: swtpm
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
  test-tcti-config:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fix-sanitizer
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          CC: gcc
          DOCKER_IMAGE: fedora-32
          TEST_TCTI_CONFIG: true
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
  test-mbedtls:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        docker_image: [ubuntu-20.04, ubuntu-22.04-mbedtls-3.1]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fix-sanitizer
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          CC: gcc
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          WITH_CRYPTO: mbed
          WITH_TCTI: mssim
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
  test-no-crypto-build:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fix-sanitizer
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          CC: gcc
          DOCKER_IMAGE: ubuntu-20.04
          WITH_CRYPTO: none
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
  test-coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fix-sanitizer
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          CC: gcc
          DOCKER_IMAGE: ubuntu-20.04
          ENABLE_COVERAGE: true
          WITH_TCTI: swtpm
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.info
          fail_ci_if_error: true
          verbose: true
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
  test-fuzz:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          DOCKER_IMAGE: fedora-32
          GEN_FUZZ: 1
          CXX: clang++
          CC: clang
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
  coverity-test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'coverity_scan')
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fix-sanitizer
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Launch Coverity Action
        uses:
          tpm2-software/ci/coverityScan@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          REPO_BRANCH: ${{ github.ref }}
          REPO_NAME: ${{ github.repository }}
          ENABLE_COVERITY: true
          DOCKER_IMAGE: ubuntu-20.04
          CC: gcc
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_SUBMISSION_EMAIL: tadeusz.struk@intel.com
      - name: failure
        if: ${{ failure() }}
        run: |
          cat $(find ../ -name config.log) || true
          cat $(find ../ -name test-suite.log) || true
