# SPDX-FileCopyrightText: 2026 Infineon Technologies AG
# SPDX-License-Identifier: BSD-2-Clause

name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *' # quote because asterisk is a special character in YAML
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run renovate to update dependencies
        uses: renovatebot/github-action@v46
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
